const db = require("./modules")
const parental = []
parental.push( {name: 'L'} )
parental.push( {name: '10'} )
parental.push( {name: '12'} )
parental.push( {name: '14'} )
parental.push( {name: '16'} )
parental.push( {name: '18'} )
return
db.parental.bulkCreate(parental)
    .then((resp)=>{ console.log("Criando classificação parental") })
    .catch(err=>  { console.log(err) })

//Category
const category = []
category.push( {name: 'Ação'} )
category.push( {name: 'Animação'} )
category.push( {name: 'Aventura'} )
category.push( {name: 'Cinema de arte'} )
category.push( {name: 'Chanchada'} )
category.push( {name: 'Comédia'} )
category.push( {name: 'Comédia romântica'} )
category.push( {name: 'Comédia dramática'} )
category.push( {name: 'Comédia de ação'} )
category.push( {name: 'Dança'} )
category.push( {name: 'Documentário'} )
category.push( {name: 'Docuficção'} )
category.push( {name: 'Drama'} )
category.push( {name: 'Espionagem'} )
category.push( {name: 'Faroeste'} )
category.push( {name: 'Fantasia científica'} )
category.push( {name: 'Ficção científica'} )
category.push( {name: 'Filmes de guerra'} )
category.push( {name: 'Musical'} )
category.push( {name: 'Filme policial'} )
category.push( {name: 'Romance'} )
category.push( {name: 'Seriado'} )
category.push( {name: 'Suspense'} )
category.push( {name: 'Terror'} )

db.category.bulkCreate(category)
    .then((resp)=>{ console.log("Criando categorias de filmes") })
    .catch(err=>  { console.log(err) })


 //Movies   
    const movies = []
    movies.push( {name: '007 Die Another day', categoryId: '22', parentalRatingID: '6', releaseYear: '2008', directorName: 'Akira Kurosawa', dubLeg: 'Legendado'   } )
    movies.push( {name: '10.000 A.C. ', categoryId: '11', parentalRatingID: '6', releaseYear: '2008', directorName: 'Alfred Hitchcock', dubLeg: 'Dublado'   } )
    movies.push( {name: '100 Escovadas antes de dormir', categoryId: '13', parentalRatingID: '5', releaseYear: '2008', directorName: 'Bernardo Bertolucci', dubLeg: 'Dublado'   } )
    movies.push( {name: '101 Dalmatas', categoryId: '13', parentalRatingID: null, releaseYear: '2008', directorName: 'Billy Wilder', dubLeg: 'Dublado'   } )
    movies.push( {name: '13 Fantasmas', categoryId: '18', parentalRatingID: null, releaseYear: '2008', directorName: 'Charlie Chaplin', dubLeg: 'Dublado'   } )
    movies.push( {name: '13 Homens e um novo segredo', categoryId: '2', parentalRatingID: '5', releaseYear: '2008', directorName: 'D.W. Griffith', dubLeg: 'Legendado'   } )
    movies.push( {name: '13° Guerreiro - Decimo Terceiro Guerreiro', categoryId: '9', parentalRatingID: '6', releaseYear: '2008', directorName: 'David Lean', dubLeg: 'Legendado'   } )
    movies.push( {name: '1408', categoryId: '17', parentalRatingID: '6', releaseYear: '2008', directorName: 'Douglas Sirk', dubLeg: 'Legendado'   } )
    movies.push( {name: '16 Quadras', categoryId: '24', parentalRatingID: '2', releaseYear: '2008', directorName: 'Ernst Lubitsch', dubLeg: 'Legendado'   } )
    movies.push( {name: '300', categoryId: '2', parentalRatingID: '5', releaseYear: '2008', directorName: 'F.W. Murnau', dubLeg: 'Legendado'   } )
    movies.push( {name: '3.10', categoryId: null, parentalRatingID: '2', releaseYear: '2008', directorName: 'Federico Fellini', dubLeg: 'Legendado'   } )
    movies.push( {name: '6° Dia - Sexto Dia', categoryId: '3', parentalRatingID: '6', releaseYear: '2008', directorName: 'Francis Ford Coppola', dubLeg: 'Legendado'   } )
    movies.push( {name: '60 Segundos', categoryId: '13', parentalRatingID: '2', releaseYear: '2008', directorName: 'François Truffaut', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A Bela e a Fera', categoryId: '21', parentalRatingID: '2', releaseYear: '2008', directorName: 'Frank Capra', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A Bussola de Ouro', categoryId: '12', parentalRatingID: '1', releaseYear: '2008', directorName: 'Fritz Lang', dubLeg: 'Legendado'   } )
    movies.push( {name: 'A Caverna', categoryId: '22', parentalRatingID: '6', releaseYear: '2005', directorName: 'George Cukor', dubLeg: 'Legendado'   } )
    movies.push( {name: 'A Cela', categoryId: null, parentalRatingID: '5', releaseYear: '2005', directorName: 'Henry King', dubLeg: 'Legendado'   } )
    movies.push( {name: 'A cor de um crime ', categoryId: '14', parentalRatingID: null, releaseYear: '2005', directorName: 'Howard Hawks', dubLeg: 'Legendado'   } )
    movies.push( {name: 'A Dama e o Vagabundo', categoryId: '11', parentalRatingID: '6', releaseYear: '2005', directorName: 'Ingmar Bergman', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A Dinastia da Espada', categoryId: '22', parentalRatingID: '2', releaseYear: '2005', directorName: 'Jacques Tati', dubLeg: 'Legendado'   } )
    movies.push( {name: 'A Era do Gelo', categoryId: '3', parentalRatingID: '1', releaseYear: '2005', directorName: 'Jean Renoir', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A Estranha Perfeita', categoryId: '9', parentalRatingID: null, releaseYear: '2005', directorName: 'Jean-Luc Godard', dubLeg: 'Legendado'   } )
    movies.push( {name: 'A Experiência', categoryId: '16', parentalRatingID: '1', releaseYear: '2005', directorName: 'John Ford', dubLeg: 'Legendado'   } )
    movies.push( {name: 'A Experiência 3 ', categoryId: '2', parentalRatingID: '5', releaseYear: '2005', directorName: 'John Huston', dubLeg: 'Legendado'   } )
    movies.push( {name: 'A Família da Noiva ', categoryId: null, parentalRatingID: '1', releaseYear: '2005', directorName: 'Jonathan Demme', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A Fonte', categoryId: '8', parentalRatingID: '2', releaseYear: '2005', directorName: 'Josef von Sternberg', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A Fuga das Galinhas', categoryId: '8', parentalRatingID: '2', releaseYear: '2005', directorName: 'Louis Malle', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A Fuga das Galinhas - Chikens Run', categoryId: '4', parentalRatingID: '1', releaseYear: '2005', directorName: 'Luis Buñuel', dubLeg: 'Legendado'   } )
    movies.push( {name: 'A Hora do Rush 3', categoryId: '19', parentalRatingID: '5', releaseYear: '2005', directorName: 'Martin Scorsese', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A Interprete.', categoryId: '8', parentalRatingID: '6', releaseYear: '2005', directorName: 'Max Ophüls', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A Lenda Do Tesouro Perdido', categoryId: null, parentalRatingID: '6', releaseYear: '2005', directorName: 'Michael Powell', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A Lenda de Beowulf', categoryId: '16', parentalRatingID: null, releaseYear: '2005', directorName: 'Nicholas Ray', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A Liga Extraordinária', categoryId: '8', parentalRatingID: null, releaseYear: '2005', directorName: 'Orson Welles', dubLeg: 'Legendado'   } )
    movies.push( {name: 'A Loja Magica de Brinquedos', categoryId: '22', parentalRatingID: '6', releaseYear: '2005', directorName: 'Otto Preminger', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A mulher do açougueiro', categoryId: '24', parentalRatingID: null, releaseYear: '2005', directorName: 'Preston Sturges', dubLeg: 'Legendado'   } )
    movies.push( {name: 'A Mumia 3 - A Tumba do Imperador Dragão', categoryId: '2', parentalRatingID: null, releaseYear: '2005', directorName: 'Robert Altman', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A Origem da vida', categoryId: '3', parentalRatingID: '1', releaseYear: '2005', directorName: 'Roman Polanski', dubLeg: 'Legendado'   } )
    movies.push( {name: 'A Outra Face', categoryId: '11', parentalRatingID: '2', releaseYear: '2005', directorName: 'Sam Peckinpah', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A Rede', categoryId: '9', parentalRatingID: '6', releaseYear: '2005', directorName: 'Satyajit Ray', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A Rede 2.0', categoryId: '7', parentalRatingID: null, releaseYear: '2005', directorName: 'Sergei Eisenstein', dubLeg: 'Legendado'   } )
    movies.push( {name: 'A Super Maquina - Knight Rider ', categoryId: '22', parentalRatingID: null, releaseYear: '2008', directorName: 'Sergio Leone', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A Segunda Chance', categoryId: '9', parentalRatingID: '5', releaseYear: '2008', directorName: 'Sidney Lumet', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A Ultima Legião', categoryId: '16', parentalRatingID: '1', releaseYear: '2008', directorName: 'Stanley Kubrick', dubLeg: 'Legendado'   } )
    movies.push( {name: 'A Volta do Todo Poderoso', categoryId: '7', parentalRatingID: '2', releaseYear: '2008', directorName: 'Steven Spielberg', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A Volta dos bravos', categoryId: '1', parentalRatingID: '1', releaseYear: '2007', directorName: 'Tim Burton', dubLeg: 'Dublado'   } )
    movies.push( {name: 'A volta dos mortos vivos 4 ', categoryId: '4', parentalRatingID: '2', releaseYear: '2007', directorName: 'Vincente Minnelli', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Acampamento do Papai', categoryId: '3', parentalRatingID: null, releaseYear: '2007', directorName: 'Werner Herzog', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Adivinhe quem vem para morrer', categoryId: '3', parentalRatingID: null, releaseYear: '2007', directorName: 'William Wyler', dubLeg: 'Dublado'   } )
    movies.push( {name: 'AeonFlux', categoryId: '13', parentalRatingID: '1', releaseYear: '2007', directorName: 'Woody Allen', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Agenda Secreta do meu Namorado', categoryId: '14', parentalRatingID: '6', releaseYear: '2007', directorName: 'Yasujiro Ozu', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Agentes De Elite', categoryId: '3', parentalRatingID: '1', releaseYear: '2007', directorName: 'Akira Kurosawa', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Akira', categoryId: '1', parentalRatingID: '1', releaseYear: '2007', directorName: 'Alfred Hitchcock', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Albergue 2 - Hostel 2', categoryId: '23', parentalRatingID: null, releaseYear: '2007', directorName: 'Bernardo Bertolucci', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Além das Linhas Inimigas', categoryId: '17', parentalRatingID: null, releaseYear: '2007', directorName: 'Billy Wilder', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Alien - O Oitavo Passageiro', categoryId: '19', parentalRatingID: null, releaseYear: '2007', directorName: 'Charlie Chaplin', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Alien vs Predador ', categoryId: '4', parentalRatingID: '2', releaseYear: '2007', directorName: 'D.W. Griffith', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Almas Atormentadas', categoryId: '24', parentalRatingID: '2', releaseYear: '2007', directorName: 'David Lean', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Alone in the dark', categoryId: null, parentalRatingID: '1', releaseYear: '2007', directorName: 'Douglas Sirk', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Alvin e os Esquilos', categoryId: null, parentalRatingID: '6', releaseYear: '2007', directorName: 'Ernst Lubitsch', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Amadeus', categoryId: '3', parentalRatingID: '1', releaseYear: '2007', directorName: 'F.W. Murnau', dubLeg: 'Dublado'   } )
    movies.push( {name: 'American Pie 2 ', categoryId: '4', parentalRatingID: '1', releaseYear: '2007', directorName: 'Federico Fellini', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Amityville', categoryId: null, parentalRatingID: '2', releaseYear: '2007', directorName: 'Francis Ford Coppola', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Amnesia', categoryId: '16', parentalRatingID: null, releaseYear: '2007', directorName: 'François Truffaut', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Amnésia', categoryId: null, parentalRatingID: null, releaseYear: '2007', directorName: 'Frank Capra', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Anatomia', categoryId: null, parentalRatingID: '5', releaseYear: '2007', directorName: 'Fritz Lang', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Animatrix', categoryId: null, parentalRatingID: null, releaseYear: '2007', directorName: 'George Cukor', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Animal 2', categoryId: '2', parentalRatingID: '6', releaseYear: '2007', directorName: 'Henry King', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Antes Só Do Que Mal Casado', categoryId: '4', parentalRatingID: '1', releaseYear: '2007', directorName: 'Howard Hawks', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Aprisionados - House of 9', categoryId: null, parentalRatingID: '5', releaseYear: '2007', directorName: 'Ingmar Bergman', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Aquamarine', categoryId: '16', parentalRatingID: '5', releaseYear: '2007', directorName: 'Jacques Tati', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Aristogatas', categoryId: '4', parentalRatingID: '6', releaseYear: '2007', directorName: 'Jean Renoir', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Armações do Amor', categoryId: '24', parentalRatingID: '2', releaseYear: '2007', directorName: 'Jean-Luc Godard', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Arrancada Final', categoryId: '3', parentalRatingID: '6', releaseYear: '2004', directorName: 'John Ford', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Arthur e os Minimoys', categoryId: '17', parentalRatingID: null, releaseYear: '2004', directorName: 'John Huston', dubLeg: 'Dublado'   } )
    movies.push( {name: 'As Loucuras de Dick & Jane ', categoryId: '18', parentalRatingID: '1', releaseYear: '2004', directorName: 'Jonathan Demme', dubLeg: 'Legendado'   } )
    movies.push( {name: 'As Panteras Detonando ', categoryId: null, parentalRatingID: null, releaseYear: '2004', directorName: 'Josef von Sternberg', dubLeg: 'Legendado'   } )
    movies.push( {name: 'As Tartarugas Ninjas - O Retorno', categoryId: '17', parentalRatingID: '1', releaseYear: '2004', directorName: 'Louis Malle', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Até a Morte', categoryId: null, parentalRatingID: null, releaseYear: '2004', directorName: 'Luis Buñuel', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Até que os parentes nos separem', categoryId: '19', parentalRatingID: '5', releaseYear: '2004', directorName: 'Martin Scorsese', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Babel', categoryId: '22', parentalRatingID: '5', releaseYear: '2004', directorName: 'Max Ophüls', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Baila Comigo', categoryId: '8', parentalRatingID: null, releaseYear: '2004', directorName: 'Michael Powell', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Bambi Edição Especial', categoryId: '24', parentalRatingID: null, releaseYear: '2004', directorName: 'Nicholas Ray', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Barbie - Fairytopia', categoryId: '13', parentalRatingID: '2', releaseYear: '2004', directorName: 'Orson Welles', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Bater ou Correr ', categoryId: '7', parentalRatingID: '6', releaseYear: '2004', directorName: 'Otto Preminger', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Bee Movie - A História de uma Abelha', categoryId: '1', parentalRatingID: null, releaseYear: '2007', directorName: 'Preston Sturges', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Beyond Citizen Kane - Muito além do cidadão Kane', categoryId: null, parentalRatingID: null, releaseYear: '2007', directorName: 'Robert Altman', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Blade I', categoryId: '8', parentalRatingID: null, releaseYear: '2007', directorName: 'Roman Polanski', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Blade II', categoryId: null, parentalRatingID: '2', releaseYear: '2007', directorName: 'Sam Peckinpah', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Blade II', categoryId: '7', parentalRatingID: '6', releaseYear: '2007', directorName: 'Satyajit Ray', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Bloodrayne', categoryId: null, parentalRatingID: null, releaseYear: '2007', directorName: 'Sergei Eisenstein', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Blow - Profissão de risco', categoryId: '12', parentalRatingID: '2', releaseYear: '2007', directorName: 'Sergio Leone', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Bob Esponja - Amigo ou Inimigo', categoryId: '4', parentalRatingID: null, releaseYear: '2008', directorName: 'Sidney Lumet', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Bob Esponja - Diversos desenhos', categoryId: '1', parentalRatingID: '2', releaseYear: '2008', directorName: 'Stanley Kubrick', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Bob Esponja o Filme', categoryId: '9', parentalRatingID: '2', releaseYear: '2008', directorName: 'Steven Spielberg', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Bope - Tropa de Elite', categoryId: '2', parentalRatingID: null, releaseYear: '2008', directorName: 'Tim Burton', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Borat', categoryId: null, parentalRatingID: '2', releaseYear: '2008', directorName: 'Vincente Minnelli', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Botas de Aço - Steel Toes', categoryId: '23', parentalRatingID: '6', releaseYear: '2006', directorName: 'Werner Herzog', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Brick', categoryId: '24', parentalRatingID: '5', releaseYear: '2006', directorName: 'William Wyler', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Brigadas do Tigre', categoryId: '11', parentalRatingID: '6', releaseYear: '2006', directorName: 'Woody Allen', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Burns Day 2002 - Motorcyle Runs', categoryId: '22', parentalRatingID: '6', releaseYear: '2006', directorName: 'Yasujiro Ozu', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Cães e Gatos', categoryId: '4', parentalRatingID: '2', releaseYear: '2006', directorName: 'Akira Kurosawa', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Cães e Gatos', categoryId: '12', parentalRatingID: null, releaseYear: '2006', directorName: 'Alfred Hitchcock', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Carros', categoryId: null, parentalRatingID: '1', releaseYear: '2006', directorName: 'Bernardo Bertolucci', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Carver ', categoryId: '6', parentalRatingID: '2', releaseYear: '2008', directorName: 'Billy Wilder', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Cavaleiros do Zodiaco - Santuario - Epis. 01 ao 73', categoryId: '1', parentalRatingID: '5', releaseYear: '2008', directorName: 'Charlie Chaplin', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Cavaleiros do Zodiaco - Asgard - Epis. 74 ao 99', categoryId: '23', parentalRatingID: '5', releaseYear: '2008', directorName: 'D.W. Griffith', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Cavaleiros do Zodiaco - Poseidom - Epis. 100 ao 114', categoryId: '17', parentalRatingID: null, releaseYear: '2008', directorName: 'David Lean', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Cavaleiros do Zodiaco - santuario - Epis. 01 ao 13', categoryId: '2', parentalRatingID: null, releaseYear: '2008', directorName: 'Douglas Sirk', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Cavaleiros do Zodiaco - inferno - Epis. 14 ao 25', categoryId: '14', parentalRatingID: '6', releaseYear: '2008', directorName: 'Ernst Lubitsch', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Cavaleiros do Zodiaco - A Grande Batalha dos Deuses (Durval)', categoryId: '21', parentalRatingID: '1', releaseYear: '2008', directorName: 'F.W. Murnau', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Cavaleiros do Zodiaco - A Lenda dos Defensores de Athena (Abel)', categoryId: '8', parentalRatingID: null, releaseYear: '2008', directorName: 'Federico Fellini', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Cavaleiros do Zodiaco - Os Guerreiros do Armagedom (Lucifer)', categoryId: '4', parentalRatingID: '5', releaseYear: '2008', directorName: 'Francis Ford Coppola', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Cavaleiros do Zodiaco - Prólogo dos Céus (Artemis)', categoryId: '4', parentalRatingID: '5', releaseYear: '2008', directorName: 'François Truffaut', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Cavaleiros do Zodiaco - Saint Seiya, o Santo Guerreiro (Éris)', categoryId: '18', parentalRatingID: '2', releaseYear: '2008', directorName: 'Frank Capra', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Caverna do Dragão - Epis. 01 ao 27', categoryId: '8', parentalRatingID: null, releaseYear: '2008', directorName: 'Fritz Lang', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Cazuza ', categoryId: '22', parentalRatingID: null, releaseYear: '2008', directorName: 'George Cukor', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Celular - um grito de socorro', categoryId: '9', parentalRatingID: '5', releaseYear: '2008', directorName: 'Henry King', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Chicago', categoryId: '2', parentalRatingID: null, releaseYear: '2008', directorName: 'Howard Hawks', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Circo Soleil Journey of Man', categoryId: '16', parentalRatingID: null, releaseYear: '2008', directorName: 'Ingmar Bergman', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Click', categoryId: '14', parentalRatingID: null, releaseYear: '2008', directorName: 'Jacques Tati', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Clube da Luta', categoryId: '18', parentalRatingID: '2', releaseYear: '2008', directorName: 'Jean Renoir', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Código Davinci', categoryId: null, parentalRatingID: null, releaseYear: '2008', directorName: 'Jean-Luc Godard', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Constantine', categoryId: null, parentalRatingID: '1', releaseYear: '2008', directorName: 'John Ford', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Contra o Tempo', categoryId: '6', parentalRatingID: '2', releaseYear: '2008', directorName: 'John Huston', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Coronado', categoryId: '11', parentalRatingID: '2', releaseYear: '2008', directorName: 'Jonathan Demme', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Creep - A plataforma do Medo', categoryId: '6', parentalRatingID: '6', releaseYear: '2008', directorName: 'Josef von Sternberg', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Criatura do Mal', categoryId: null, parentalRatingID: '1', releaseYear: '2008', directorName: 'Louis Malle', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Criminal Minds - 1a. Temporada', categoryId: '18', parentalRatingID: '1', releaseYear: '2008', directorName: 'Luis Buñuel', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Crocodilo Dundee em Hollywood', categoryId: '22', parentalRatingID: null, releaseYear: '2008', directorName: 'Martin Scorsese', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Crusty Demons of Dirty 3', categoryId: '16', parentalRatingID: '1', releaseYear: '2008', directorName: 'Max Ophüls', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Crusty Demons of Dirty 6', categoryId: '1', parentalRatingID: null, releaseYear: '2008', directorName: 'Michael Powell', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Cry Wolf', categoryId: null, parentalRatingID: '5', releaseYear: '2008', directorName: 'Nicholas Ray', dubLeg: 'Legendado'   } )
    movies.push( {name: 'CSI 1 Temp. Epis. 01 ao 12', categoryId: '17', parentalRatingID: '2', releaseYear: '2008', directorName: 'Orson Welles', dubLeg: 'Legendado'   } )
    movies.push( {name: 'CSI 1 Temp. Epis. 13 ao 23', categoryId: '16', parentalRatingID: null, releaseYear: '2008', directorName: 'Otto Preminger', dubLeg: 'Legendado'   } )
    movies.push( {name: 'CSI 2 Temp. Epis. 01 ao 12', categoryId: '11', parentalRatingID: null, releaseYear: '2008', directorName: 'Preston Sturges', dubLeg: 'Legendado'   } )
    movies.push( {name: 'CSI 2 Temp. Epis. 13 ao 23', categoryId: '24', parentalRatingID: null, releaseYear: '2008', directorName: 'Robert Altman', dubLeg: 'Legendado'   } )
    movies.push( {name: 'CSI 3 Temp. Epis. 01 ao 12', categoryId: '11', parentalRatingID: '1', releaseYear: '2008', directorName: 'Roman Polanski', dubLeg: 'Legendado'   } )
    movies.push( {name: 'CSI 3 Temp. Epis. 13 ao 23', categoryId: null, parentalRatingID: '1', releaseYear: '2008', directorName: 'Sam Peckinpah', dubLeg: 'Legendado'   } )
    movies.push( {name: 'CSI 4 Temp. Epis. 01 ao 12', categoryId: '8', parentalRatingID: null, releaseYear: '2008', directorName: 'Satyajit Ray', dubLeg: 'Legendado'   } )
    movies.push( {name: 'CSI 4 Temp. Epis. 13 ao 23', categoryId: '12', parentalRatingID: '2', releaseYear: '2008', directorName: 'Sergei Eisenstein', dubLeg: 'Legendado'   } )
    movies.push( {name: 'CSI 5 Temp. Epis. 01 ao 12', categoryId: '1', parentalRatingID: '6', releaseYear: '2008', directorName: 'Sergio Leone', dubLeg: 'Legendado'   } )
    movies.push( {name: 'CSI 5 Temp. Epis. 13 ao 23', categoryId: '24', parentalRatingID: '5', releaseYear: '2008', directorName: 'Sidney Lumet', dubLeg: 'Legendado'   } )
    movies.push( {name: 'CSI 6 Temp. Epis. 01 ao 12', categoryId: '19', parentalRatingID: null, releaseYear: '2008', directorName: 'Stanley Kubrick', dubLeg: 'Legendado'   } )
    movies.push( {name: 'CSI 6 Temp. Epis. 13 ao 23', categoryId: '16', parentalRatingID: '5', releaseYear: '2008', directorName: 'Steven Spielberg', dubLeg: 'Legendado'   } )
    movies.push( {name: 'CSI 7 Temp. Epis. 01 ao 24', categoryId: '18', parentalRatingID: null, releaseYear: '2008', directorName: 'Tim Burton', dubLeg: 'Legendado'   } )
    movies.push( {name: 'CSI 8 Temp. Epis. 01 ao 17', categoryId: '2', parentalRatingID: null, releaseYear: '2008', directorName: 'Vincente Minnelli', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Cubix - Desafio na cidade dos Rôbos ', categoryId: '6', parentalRatingID: null, releaseYear: '2008', directorName: 'Werner Herzog', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Curioso George', categoryId: null, parentalRatingID: '2', releaseYear: '2008', directorName: 'William Wyler', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Curtas Pixar', categoryId: '14', parentalRatingID: null, releaseYear: '2008', directorName: 'Woody Allen', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Curtindo a Vida Adoidado - Ferris Bueller Day´s Off', categoryId: '1', parentalRatingID: '1', releaseYear: '1986', directorName: 'Yasujiro Ozu', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Dama na Agua', categoryId: '7', parentalRatingID: '6', releaseYear: '1986', directorName: 'Akira Kurosawa', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Darklight - O Poder da Escuridão', categoryId: '9', parentalRatingID: '5', releaseYear: '2004', directorName: 'Alfred Hitchcock', dubLeg: 'Dublado'   } )
    movies.push( {name: 'De volta para o futuro I', categoryId: '16', parentalRatingID: '1', releaseYear: '2004', directorName: 'Bernardo Bertolucci', dubLeg: 'Legendado'   } )
    movies.push( {name: 'De volta para o futuro II', categoryId: '13', parentalRatingID: '2', releaseYear: '2004', directorName: 'Billy Wilder', dubLeg: 'Legendado'   } )
    movies.push( {name: 'De volta para o futuro III', categoryId: '4', parentalRatingID: '1', releaseYear: '2004', directorName: 'Charlie Chaplin', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Demon Hunter', categoryId: '8', parentalRatingID: '6', releaseYear: '2004', directorName: 'D.W. Griffith', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Desejo e reparação', categoryId: '16', parentalRatingID: null, releaseYear: '2004', directorName: 'David Lean', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Despertar de um Crime', categoryId: '13', parentalRatingID: null, releaseYear: '2006', directorName: 'Douglas Sirk', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Deu a Louca na Cinderela - Desenho', categoryId: '13', parentalRatingID: null, releaseYear: '2006', directorName: 'Ernst Lubitsch', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Dexter - 1a. Temporada - 01 ao 12', categoryId: null, parentalRatingID: '2', releaseYear: '2006', directorName: 'F.W. Murnau', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Dia de Ira ', categoryId: '1', parentalRatingID: '6', releaseYear: '2006', directorName: 'Federico Fellini', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Diante do Trono - Show Gospel', categoryId: '12', parentalRatingID: '1', releaseYear: '2006', directorName: 'Francis Ford Coppola', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Diario de uma paixão', categoryId: '19', parentalRatingID: '6', releaseYear: '2004', directorName: 'François Truffaut', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Dinheiro Sujo', categoryId: '11', parentalRatingID: '6', releaseYear: '2004', directorName: 'Frank Capra', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Dinossauros', categoryId: '17', parentalRatingID: null, releaseYear: '2004', directorName: 'Fritz Lang', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Doom', categoryId: '3', parentalRatingID: '6', releaseYear: '2004', directorName: 'George Cukor', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Doom', categoryId: null, parentalRatingID: null, releaseYear: '2004', directorName: 'Henry King', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Dragon Wars D-War', categoryId: '6', parentalRatingID: '2', releaseYear: '2008', directorName: 'Howard Hawks', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Dreamgirls', categoryId: '7', parentalRatingID: null, releaseYear: '2006', directorName: 'Ingmar Bergman', dubLeg: 'Legendado'   } )
    movies.push( {name: 'D-Tox ', categoryId: '4', parentalRatingID: null, releaseYear: '2006', directorName: 'Jacques Tati', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Duas Vidas', categoryId: '7', parentalRatingID: null, releaseYear: '2006', directorName: 'Jean Renoir', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Duck Tales O tesouro da lampada perdida ', categoryId: '23', parentalRatingID: '5', releaseYear: '2006', directorName: 'Jean-Luc Godard', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Duma', categoryId: '6', parentalRatingID: '2', releaseYear: '2006', directorName: 'John Ford', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Duro de Matar 4.0', categoryId: '24', parentalRatingID: '6', releaseYear: '2006', directorName: 'John Huston', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Eclipse Mortal', categoryId: null, parentalRatingID: '1', releaseYear: '2006', directorName: 'Jonathan Demme', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Efeito Borboleta', categoryId: '22', parentalRatingID: null, releaseYear: '2006', directorName: 'Josef von Sternberg', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Efeito Borboleta 2', categoryId: '12', parentalRatingID: null, releaseYear: '2006', directorName: 'Louis Malle', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Efeito Colateral ', categoryId: '7', parentalRatingID: null, releaseYear: '2006', directorName: 'Luis Buñuel', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Elektra', categoryId: '6', parentalRatingID: '1', releaseYear: '2006', directorName: 'Martin Scorsese', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Elizabeth A Era de Ouro', categoryId: '24', parentalRatingID: null, releaseYear: '2007', directorName: 'Max Ophüls', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Encantada', categoryId: '3', parentalRatingID: '1', releaseYear: '2008', directorName: 'Michael Powell', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Em Busca do Vale Encantado - Viagem a Agua Grande', categoryId: '14', parentalRatingID: null, releaseYear: '2008', directorName: 'Nicholas Ray', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Endiabrado (Bedazzled) ', categoryId: null, parentalRatingID: null, releaseYear: '2000', directorName: 'Orson Welles', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Enigma', categoryId: '19', parentalRatingID: null, releaseYear: '2000', directorName: 'Otto Preminger', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Equilibrium', categoryId: '24', parentalRatingID: '6', releaseYear: '2000', directorName: 'Preston Sturges', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Era do Gelo', categoryId: '18', parentalRatingID: '5', releaseYear: '2000', directorName: 'Robert Altman', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Era do Gelo', categoryId: '6', parentalRatingID: '1', releaseYear: '2000', directorName: 'Roman Polanski', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Era do Gelo 2', categoryId: '8', parentalRatingID: '1', releaseYear: '2000', directorName: 'Sam Peckinpah', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Eragon', categoryId: '16', parentalRatingID: '2', releaseYear: '2006', directorName: 'Satyajit Ray', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Escorpião Rei', categoryId: '9', parentalRatingID: '2', releaseYear: '2006', directorName: 'Sergei Eisenstein', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Escorregando para a Glória', categoryId: null, parentalRatingID: '5', releaseYear: '2007', directorName: 'Sergio Leone', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Espanta Tubarões', categoryId: '12', parentalRatingID: null, releaseYear: '2007', directorName: 'Sidney Lumet', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Espião por acidente', categoryId: null, parentalRatingID: '1', releaseYear: '2007', directorName: 'Stanley Kubrick', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Eterno Amor', categoryId: '18', parentalRatingID: '5', releaseYear: '2007', directorName: 'Steven Spielberg', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Eu Cristiane F. 13 Anos, drogada e prostituida', categoryId: '14', parentalRatingID: '6', releaseYear: '2007', directorName: 'Tim Burton', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Eu e as Mulheres', categoryId: '7', parentalRatingID: '1', releaseYear: '2007', directorName: 'Vincente Minnelli', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Eu Os Declaro Marido e Larry', categoryId: '6', parentalRatingID: null, releaseYear: '2007', directorName: 'Werner Herzog', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Eu Robô', categoryId: null, parentalRatingID: '1', releaseYear: '2007', directorName: 'William Wyler', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Eu sou a Lenda', categoryId: '7', parentalRatingID: '5', releaseYear: '2007', directorName: 'Woody Allen', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Evolução', categoryId: '21', parentalRatingID: '6', releaseYear: '2007', directorName: 'Yasujiro Ozu', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Exorcista - O inicio', categoryId: '7', parentalRatingID: '5', releaseYear: '2007', directorName: 'Akira Kurosawa', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Fallen - 3 episodios', categoryId: '1', parentalRatingID: '2', releaseYear: '2007', directorName: 'Alfred Hitchcock', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Fim dos Tempos ', categoryId: '8', parentalRatingID: null, releaseYear: '2007', directorName: 'Bernardo Bertolucci', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Final Fantasy', categoryId: '16', parentalRatingID: '5', releaseYear: '2007', directorName: 'Billy Wilder', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Firewall ', categoryId: '7', parentalRatingID: null, releaseYear: '2007', directorName: 'Charlie Chaplin', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Flight 93 ', categoryId: '11', parentalRatingID: '5', releaseYear: '2007', directorName: 'D.W. Griffith', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Fora de Controle', categoryId: '14', parentalRatingID: '2', releaseYear: '2007', directorName: 'David Lean', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Freddy vs Jason', categoryId: '3', parentalRatingID: '2', releaseYear: '2007', directorName: 'Douglas Sirk', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Friends - 1 temp. epis. 1 ao 24', categoryId: '7', parentalRatingID: null, releaseYear: '2007', directorName: 'Ernst Lubitsch', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Friends - 2 temp. epis. 1 ao 24', categoryId: '14', parentalRatingID: null, releaseYear: '2007', directorName: 'F.W. Murnau', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Friends - 3 temp. epis. 1 ao 24', categoryId: null, parentalRatingID: null, releaseYear: '2007', directorName: 'Federico Fellini', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Gabriel A Vinganca de Um Anjo', categoryId: '11', parentalRatingID: '2', releaseYear: '2007', directorName: 'Francis Ford Coppola', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Garfield 2', categoryId: '17', parentalRatingID: '6', releaseYear: '2007', directorName: 'François Truffaut', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Garotas Rebeldes - Niñas Mal', categoryId: '18', parentalRatingID: '1', releaseYear: '2007', directorName: 'Frank Capra', dubLeg: 'Dublado'   } )
    movies.push( {name: 'George e o dragão', categoryId: '23', parentalRatingID: '1', releaseYear: '2007', directorName: 'Fritz Lang', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Ghost Rider', categoryId: '1', parentalRatingID: '2', releaseYear: '2007', directorName: 'George Cukor', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Gigolo Europeu por acidente', categoryId: '11', parentalRatingID: '1', releaseYear: '2007', directorName: 'Henry King', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Gladiador', categoryId: '2', parentalRatingID: null, releaseYear: '2007', directorName: 'Howard Hawks', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Grilled', categoryId: '4', parentalRatingID: '5', releaseYear: '2007', directorName: 'Ingmar Bergman', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Gritos do além', categoryId: '13', parentalRatingID: '5', releaseYear: '2007', directorName: 'Jacques Tati', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Guerra dos Mundos - War of the Worlds', categoryId: '8', parentalRatingID: null, releaseYear: '2005', directorName: 'Jean Renoir', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Há Vagas', categoryId: null, parentalRatingID: '5', releaseYear: '2005', directorName: 'Jean-Luc Godard', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Hackers', categoryId: null, parentalRatingID: '5', releaseYear: '2005', directorName: 'John Ford', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Hancock', categoryId: null, parentalRatingID: '5', releaseYear: '2008', directorName: 'John Huston', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Hannibal ', categoryId: '22', parentalRatingID: '1', releaseYear: '2008', directorName: 'Jonathan Demme', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Hannibal Rising', categoryId: '11', parentalRatingID: '5', releaseYear: '2008', directorName: 'Josef von Sternberg', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Happy Feet - O Pinguim', categoryId: '4', parentalRatingID: null, releaseYear: '2006', directorName: 'Louis Malle', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Harry Potter e a Câmara Secreta', categoryId: '22', parentalRatingID: '6', releaseYear: '2006', directorName: 'Luis Buñuel', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Harry Potter e a Ordem da Fênix', categoryId: '22', parentalRatingID: '6', releaseYear: '2006', directorName: 'Martin Scorsese', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Harry Potter e o calice de Fogo', categoryId: '16', parentalRatingID: '2', releaseYear: '2006', directorName: 'Max Ophüls', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Heavy Metal', categoryId: '4', parentalRatingID: null, releaseYear: '2006', directorName: 'Michael Powell', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Hellraiser 1 ', categoryId: '13', parentalRatingID: '5', releaseYear: '2006', directorName: 'Nicholas Ray', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Hellraiser 2', categoryId: '21', parentalRatingID: '1', releaseYear: '2006', directorName: 'Orson Welles', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Hellsing - Epis, 01 ao 13', categoryId: '16', parentalRatingID: '5', releaseYear: '2006', directorName: 'Otto Preminger', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Heroes - 1 temp. epis. 1 ao 23', categoryId: '12', parentalRatingID: '6', releaseYear: '2006', directorName: 'Preston Sturges', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Heroes - 2 temp. epis. 1 ao 11', categoryId: '11', parentalRatingID: null, releaseYear: '2006', directorName: 'Robert Altman', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Heroi', categoryId: '18', parentalRatingID: '5', releaseYear: '2006', directorName: 'Roman Polanski', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Herói - Hero Wanted', categoryId: '22', parentalRatingID: '6', releaseYear: '2007', directorName: 'Sam Peckinpah', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Homem Aranha', categoryId: '9', parentalRatingID: '1', releaseYear: '2007', directorName: 'Satyajit Ray', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Homem de Ferro - Iron Man.', categoryId: '4', parentalRatingID: null, releaseYear: '2008', directorName: 'Sergei Eisenstein', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Homens de Preto 2', categoryId: null, parentalRatingID: null, releaseYear: '2008', directorName: 'Sergio Leone', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Horton e o Mundo dos Quem!', categoryId: '4', parentalRatingID: null, releaseYear: '2008', directorName: 'Sidney Lumet', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Hot.Wheels Acceleracers A Velocidade do Silencio', categoryId: '21', parentalRatingID: null, releaseYear: '2005', directorName: 'Stanley Kubrick', dubLeg: 'Dublado'   } )
    movies.push( {name: 'House - 1a. Temporada - Epis. 01 ao 10', categoryId: '9', parentalRatingID: null, releaseYear: '2005', directorName: 'Steven Spielberg', dubLeg: 'Legendado'   } )
    movies.push( {name: 'House - 1a. Temporada - Epis. 11 ao 22', categoryId: '9', parentalRatingID: '5', releaseYear: '2005', directorName: 'Tim Burton', dubLeg: 'Legendado'   } )
    movies.push( {name: 'House of The Dead', categoryId: null, parentalRatingID: '1', releaseYear: '2005', directorName: 'Vincente Minnelli', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Hulk', categoryId: '24', parentalRatingID: '1', releaseYear: '2005', directorName: 'Werner Herzog', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Indiana Jones e a ultima cruzada', categoryId: '7', parentalRatingID: '1', releaseYear: '2005', directorName: 'William Wyler', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Indiana Jones e o Reino da Caveira de Cristal ', categoryId: '2', parentalRatingID: '5', releaseYear: '2008', directorName: 'Woody Allen', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Insektors', categoryId: '4', parentalRatingID: null, releaseYear: '2008', directorName: 'Yasujiro Ozu', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Insonia', categoryId: '2', parentalRatingID: '5', releaseYear: '2008', directorName: 'Akira Kurosawa', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Inteligência Artificial', categoryId: '1', parentalRatingID: '5', releaseYear: '2008', directorName: 'Alfred Hitchcock', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Invasão - Epis. 01 ao 22', categoryId: null, parentalRatingID: '5', releaseYear: '2008', directorName: 'Bernardo Bertolucci', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Irmão Urso', categoryId: null, parentalRatingID: '6', releaseYear: '2008', directorName: 'Billy Wilder', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Jet Li - contra o tempo', categoryId: '1', parentalRatingID: '6', releaseYear: '2008', directorName: 'Charlie Chaplin', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Jogo Subterrâneo', categoryId: '9', parentalRatingID: null, releaseYear: '2008', directorName: 'D.W. Griffith', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Jogos Mortais', categoryId: '12', parentalRatingID: '2', releaseYear: '2008', directorName: 'David Lean', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Jogos Mortais 2', categoryId: null, parentalRatingID: '6', releaseYear: '2008', directorName: 'Douglas Sirk', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Jogos Mortais 2', categoryId: '7', parentalRatingID: '5', releaseYear: '2008', directorName: 'Ernst Lubitsch', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Jogos Mortais 3', categoryId: '22', parentalRatingID: '5', releaseYear: '2008', directorName: 'F.W. Murnau', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Jogos Sangrentos', categoryId: '14', parentalRatingID: null, releaseYear: '2008', directorName: 'Federico Fellini', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Jovens, Doidos E Alucinados - Drunken Jackasses The Quest', categoryId: '14', parentalRatingID: '5', releaseYear: '2003', directorName: 'Francis Ford Coppola', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Juizo Final - Doomsday', categoryId: '9', parentalRatingID: '5', releaseYear: '2008', directorName: 'François Truffaut', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Jumper', categoryId: '14', parentalRatingID: '1', releaseYear: '2008', directorName: 'Frank Capra', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Juventude Perdida', categoryId: '21', parentalRatingID: null, releaseYear: '2008', directorName: 'Fritz Lang', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Jurassic Park 1 ', categoryId: '11', parentalRatingID: null, releaseYear: '2008', directorName: 'George Cukor', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Jurassic Park 3', categoryId: null, parentalRatingID: '5', releaseYear: '2008', directorName: 'Henry King', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Jurassic Park 3', categoryId: '18', parentalRatingID: '5', releaseYear: '2008', directorName: 'Howard Hawks', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Justiça a qualquer preço', categoryId: '11', parentalRatingID: '5', releaseYear: '2008', directorName: 'Ingmar Bergman', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Kanguru Jack', categoryId: '23', parentalRatingID: '1', releaseYear: '2008', directorName: 'Jacques Tati', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Kidulthood', categoryId: '17', parentalRatingID: null, releaseYear: '2008', directorName: 'Jean Renoir', dubLeg: 'Legendado'   } )
    movies.push( {name: 'King Kong ', categoryId: '2', parentalRatingID: '5', releaseYear: '2008', directorName: 'Jean-Luc Godard', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Kung Fu são (Kung fu hustler)', categoryId: '7', parentalRatingID: null, releaseYear: '2008', directorName: 'John Ford', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Lagrimas do Sol', categoryId: '4', parentalRatingID: '6', releaseYear: '2008', directorName: 'John Huston', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Licença para casar', categoryId: '2', parentalRatingID: null, releaseYear: '2007', directorName: 'Jonathan Demme', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Lições De Vida', categoryId: '21', parentalRatingID: null, releaseYear: '2007', directorName: 'Josef von Sternberg', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Liga da Justiça Unlimited 1 temp. epis. 1 ao 11', categoryId: '23', parentalRatingID: '5', releaseYear: '2007', directorName: 'Louis Malle', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Ligeiramente Gravidos', categoryId: '16', parentalRatingID: null, releaseYear: '2007', directorName: 'Luis Buñuel', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Lilo & Stitch', categoryId: '16', parentalRatingID: '2', releaseYear: '2007', directorName: 'Martin Scorsese', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Limite Vertical', categoryId: '9', parentalRatingID: null, releaseYear: '2007', directorName: 'Max Ophüls', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Lodoss - Epis. 1 ao 13', categoryId: '2', parentalRatingID: null, releaseYear: '2007', directorName: 'Michael Powell', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Lost 2 Temporada - Episodio 01 ao 11', categoryId: '14', parentalRatingID: null, releaseYear: '2007', directorName: 'Nicholas Ray', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Lost 2 Temporada - Episodio 12 ao 24', categoryId: '11', parentalRatingID: '5', releaseYear: '2007', directorName: 'Orson Welles', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Lost 3 Temporada - Episodio 00 ao 23', categoryId: '3', parentalRatingID: '1', releaseYear: '2007', directorName: 'Otto Preminger', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Lost 4 Temporada - Episodio 01 ao 13', categoryId: '14', parentalRatingID: null, releaseYear: '2007', directorName: 'Preston Sturges', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Loucuras da Idade Média ', categoryId: '9', parentalRatingID: null, releaseYear: '2007', directorName: 'Robert Altman', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Loucuras na Idade Média', categoryId: '18', parentalRatingID: '1', releaseYear: '2007', directorName: 'Roman Polanski', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Mac Gyver - 1 temp. epis. 1 ao 4', categoryId: '11', parentalRatingID: '2', releaseYear: '2007', directorName: 'Sam Peckinpah', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Madagascar', categoryId: null, parentalRatingID: '5', releaseYear: '2007', directorName: 'Satyajit Ray', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Madagascar ', categoryId: '8', parentalRatingID: '1', releaseYear: '2007', directorName: 'Sergei Eisenstein', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Madrugada dos Mortos', categoryId: '2', parentalRatingID: '5', releaseYear: '2007', directorName: 'Sergio Leone', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Mandando Bala (Shoot Em Up) ', categoryId: '21', parentalRatingID: null, releaseYear: '2007', directorName: 'Sidney Lumet', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Máquina Quase Mortífera  ( Loaded Weapon 1) ', categoryId: '16', parentalRatingID: '2', releaseYear: '1993', directorName: 'Stanley Kubrick', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Matrix', categoryId: '17', parentalRatingID: '2', releaseYear: '1993', directorName: 'Steven Spielberg', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Matrix Reloaded', categoryId: '6', parentalRatingID: null, releaseYear: '1993', directorName: 'Tim Burton', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Medo da Verdade - Gone Baby Gone', categoryId: '11', parentalRatingID: '1', releaseYear: '2007', directorName: 'Vincente Minnelli', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Menina Má.com -Hard Candy', categoryId: '11', parentalRatingID: '1', releaseYear: '2007', directorName: 'Werner Herzog', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Meu nome não é Johnny', categoryId: '9', parentalRatingID: '1', releaseYear: '2008', directorName: 'William Wyler', dubLeg: 'Dublado'   } )
    movies.push( {name: 'MIB II', categoryId: '7', parentalRatingID: null, releaseYear: '2008', directorName: 'Woody Allen', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Mimzy - A Chave do Universo', categoryId: '1', parentalRatingID: '5', releaseYear: '2007', directorName: 'Yasujiro Ozu', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Minotauro', categoryId: '7', parentalRatingID: '5', releaseYear: '2007', directorName: 'Akira Kurosawa', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Minha Mãe Quer que Eu Case', categoryId: null, parentalRatingID: null, releaseYear: '2007', directorName: 'Alfred Hitchcock', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Miss Simpatia', categoryId: null, parentalRatingID: '1', releaseYear: '2007', directorName: 'Bernardo Bertolucci', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Missão Impossivel 2', categoryId: null, parentalRatingID: '2', releaseYear: '2007', directorName: 'Billy Wilder', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Missão Impossivel 3', categoryId: '17', parentalRatingID: null, releaseYear: '2007', directorName: 'Charlie Chaplin', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Mogli 2', categoryId: '16', parentalRatingID: '6', releaseYear: '2007', directorName: 'D.W. Griffith', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Monstros S.A.', categoryId: '8', parentalRatingID: null, releaseYear: '2007', directorName: 'David Lean', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Monstros S.A.', categoryId: '1', parentalRatingID: '1', releaseYear: '2007', directorName: 'Douglas Sirk', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Monty Python - Holywood Bowl', categoryId: null, parentalRatingID: '5', releaseYear: '2007', directorName: 'Ernst Lubitsch', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Moranguinho - O Filme - Doces Sonhos', categoryId: '14', parentalRatingID: '6', releaseYear: '2007', directorName: 'F.W. Murnau', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Motoqueiro Fantasma', categoryId: '12', parentalRatingID: '2', releaseYear: '2007', directorName: 'Federico Fellini', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Motoqueiros Selvagens', categoryId: '19', parentalRatingID: '2', releaseYear: '2007', directorName: 'Francis Ford Coppola', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Mulan 2', categoryId: null, parentalRatingID: null, releaseYear: '2007', directorName: 'François Truffaut', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Na companhia do medo', categoryId: '6', parentalRatingID: '6', releaseYear: '2007', directorName: 'Frank Capra', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Não é outro besteirol americano', categoryId: null, parentalRatingID: '1', releaseYear: '2007', directorName: 'Fritz Lang', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Natal do Mickey', categoryId: '24', parentalRatingID: null, releaseYear: '2007', directorName: 'George Cukor', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Nausea Total - Bad Taste', categoryId: null, parentalRatingID: '2', releaseYear: '1978', directorName: 'Henry King', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Navio Fantasma', categoryId: '19', parentalRatingID: '5', releaseYear: '1978', directorName: 'Howard Hawks', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Nem que a vaca tussa', categoryId: '18', parentalRatingID: '2', releaseYear: '1978', directorName: 'Ingmar Bergman', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Neve Pra Cachorro', categoryId: '22', parentalRatingID: null, releaseYear: '1978', directorName: 'Jacques Tati', dubLeg: 'Dublado'   } )
    movies.push( {name: 'New World Disorder - Mountain Bike', categoryId: '16', parentalRatingID: null, releaseYear: '1978', directorName: 'Jean Renoir', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Next O Vidente', categoryId: '1', parentalRatingID: '1', releaseYear: '1978', directorName: 'Jean-Luc Godard', dubLeg: 'Dublado'   } )
    movies.push( {name: 'No Balanço do Amor', categoryId: null, parentalRatingID: '1', releaseYear: '2001', directorName: 'John Ford', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Noite no Museu', categoryId: '16', parentalRatingID: null, releaseYear: '2001', directorName: 'John Huston', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Norbit', categoryId: '1', parentalRatingID: '2', releaseYear: '2001', directorName: 'Jonathan Demme', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Novo Mundo', categoryId: '19', parentalRatingID: '2', releaseYear: '2001', directorName: 'Josef von Sternberg', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Agente', categoryId: '9', parentalRatingID: '2', releaseYear: '2007', directorName: 'Louis Malle', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Amor Não Tira Férias', categoryId: '11', parentalRatingID: '1', releaseYear: '2007', directorName: 'Luis Buñuel', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Amor nos Tempos de Cólera', categoryId: '11', parentalRatingID: '6', releaseYear: '2007', directorName: 'Martin Scorsese', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Amor pode dar certo', categoryId: '8', parentalRatingID: '5', releaseYear: '2007', directorName: 'Max Ophüls', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Apanhador de Sonhos (Dreamcatcher)', categoryId: '12', parentalRatingID: '5', releaseYear: '2003', directorName: 'Michael Powell', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Apocalipse', categoryId: '19', parentalRatingID: '2', releaseYear: '2003', directorName: 'Nicholas Ray', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Atirador', categoryId: '14', parentalRatingID: '5', releaseYear: '2003', directorName: 'Orson Welles', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Beijo do Dragão - Kiss of the dragon ', categoryId: '19', parentalRatingID: null, releaseYear: '2003', directorName: 'Otto Preminger', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Bicho Vai pegar', categoryId: null, parentalRatingID: '5', releaseYear: '2003', directorName: 'Preston Sturges', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Chamado', categoryId: '7', parentalRatingID: '6', releaseYear: '2003', directorName: 'Robert Altman', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Chamado 2', categoryId: null, parentalRatingID: '2', releaseYear: '2003', directorName: 'Roman Polanski', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O clan das adagas voadoras', categoryId: '16', parentalRatingID: '6', releaseYear: '2003', directorName: 'Sam Peckinpah', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Código Da Vinci (The Da Vinci Code) ', categoryId: '14', parentalRatingID: '1', releaseYear: '2006', directorName: 'Satyajit Ray', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Colecionador de Ossos', categoryId: '12', parentalRatingID: null, releaseYear: '2006', directorName: 'Sergei Eisenstein', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Crime Perfeito', categoryId: '4', parentalRatingID: '2', releaseYear: '2006', directorName: 'Sergio Leone', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Cruzeiro das Loucas', categoryId: null, parentalRatingID: null, releaseYear: '2006', directorName: 'Sidney Lumet', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Demolidor', categoryId: '21', parentalRatingID: '6', releaseYear: '2006', directorName: 'Stanley Kubrick', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Diabo Veste Prada', categoryId: '6', parentalRatingID: '6', releaseYear: '2006', directorName: 'Steven Spielberg', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Enigma da Pirâmide - Young Sherlock Holmes', categoryId: null, parentalRatingID: '6', releaseYear: '1985', directorName: 'Tim Burton', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O exorcismo de Emily Rose', categoryId: '21', parentalRatingID: null, releaseYear: '1985', directorName: 'Vincente Minnelli', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Gangster - American Gangster', categoryId: '18', parentalRatingID: '6', releaseYear: '2008', directorName: 'Werner Herzog', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Guarda Costas 2 - The bodyguard 2', categoryId: '3', parentalRatingID: '2', releaseYear: '2007', directorName: 'William Wyler', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Guardião', categoryId: '14', parentalRatingID: '2', releaseYear: '2007', directorName: 'Woody Allen', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Grande Furo', categoryId: '18', parentalRatingID: null, releaseYear: '2007', directorName: 'Yasujiro Ozu', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Homem sem Sombra', categoryId: '13', parentalRatingID: null, releaseYear: '2007', directorName: 'Akira Kurosawa', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Homem de Ferro', categoryId: '24', parentalRatingID: '6', releaseYear: '2007', directorName: 'Alfred Hitchcock', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Ilusionista', categoryId: null, parentalRatingID: null, releaseYear: '2006', directorName: 'Bernardo Bertolucci', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Implacavel', categoryId: '22', parentalRatingID: '2', releaseYear: '2006', directorName: 'Billy Wilder', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O incrivel Hulk - The Incredible Hulk', categoryId: null, parentalRatingID: '2', releaseYear: '2008', directorName: 'Charlie Chaplin', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Invisivel', categoryId: '17', parentalRatingID: '2', releaseYear: '2008', directorName: 'D.W. Griffith', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Mar não esta pra peixe', categoryId: '16', parentalRatingID: '1', releaseYear: '2008', directorName: 'David Lean', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Matador', categoryId: '9', parentalRatingID: null, releaseYear: '2008', directorName: 'Douglas Sirk', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Novo Mundo', categoryId: '12', parentalRatingID: '5', releaseYear: '2008', directorName: 'Ernst Lubitsch', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Numero 23', categoryId: '8', parentalRatingID: null, releaseYear: '2008', directorName: 'F.W. Murnau', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Outro lado do céu', categoryId: '24', parentalRatingID: '2', releaseYear: '2008', directorName: 'Federico Fellini', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Patriota ', categoryId: '12', parentalRatingID: null, releaseYear: '2008', directorName: 'Francis Ford Coppola', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Pequenino', categoryId: '1', parentalRatingID: '6', releaseYear: '2008', directorName: 'François Truffaut', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Procurado (Wanted)', categoryId: null, parentalRatingID: null, releaseYear: '2008', directorName: 'Frank Capra', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Reino', categoryId: '18', parentalRatingID: '1', releaseYear: '2007', directorName: 'Fritz Lang', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O REINO PROIBIDO (The Forbidden Kingdom)', categoryId: '17', parentalRatingID: null, releaseYear: '2007', directorName: 'George Cukor', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Segredo - The Secret', categoryId: '17', parentalRatingID: null, releaseYear: '2007', directorName: 'Henry King', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Senhor das Armas', categoryId: '2', parentalRatingID: '1', releaseYear: '2005', directorName: 'Howard Hawks', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Sentinela', categoryId: '8', parentalRatingID: '2', releaseYear: '2005', directorName: 'Ingmar Bergman', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Todo Poderoso', categoryId: '11', parentalRatingID: '2', releaseYear: '2005', directorName: 'Jacques Tati', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Trapaceiro ', categoryId: '22', parentalRatingID: '5', releaseYear: '2005', directorName: 'Jean Renoir', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Ultimo Samurai', categoryId: '2', parentalRatingID: '6', releaseYear: '2005', directorName: 'Jean-Luc Godard', dubLeg: 'Legendado'   } )
    movies.push( {name: 'O Unico - The One - Jet Li', categoryId: '4', parentalRatingID: '1', releaseYear: '2005', directorName: 'John Ford', dubLeg: 'Dublado'   } )
    movies.push( {name: 'O Vingador', categoryId: '9', parentalRatingID: '6', releaseYear: '2005', directorName: 'John Huston', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Olhos Famintos 1', categoryId: '23', parentalRatingID: '6', releaseYear: '2005', directorName: 'Jonathan Demme', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Olhos Famintos 2', categoryId: '13', parentalRatingID: '5', releaseYear: '2005', directorName: 'Josef von Sternberg', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Ong Bak', categoryId: '23', parentalRatingID: '6', releaseYear: '2005', directorName: 'Louis Malle', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Onze Homens e Um Segredo - Ocean´s Eleven', categoryId: '24', parentalRatingID: null, releaseYear: '2005', directorName: 'Luis Buñuel', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Os Anjinhos ', categoryId: null, parentalRatingID: '5', releaseYear: '2005', directorName: 'Martin Scorsese', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Os Condenados', categoryId: '18', parentalRatingID: '2', releaseYear: '2007', directorName: 'Max Ophüls', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Os Fora-da-Lei ', categoryId: '21', parentalRatingID: null, releaseYear: '2007', directorName: 'Michael Powell', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Os Incriveis', categoryId: null, parentalRatingID: '2', releaseYear: '2007', directorName: 'Nicholas Ray', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Os Incriveis', categoryId: '19', parentalRatingID: '5', releaseYear: '2007', directorName: 'Orson Welles', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Os Incriveis', categoryId: '19', parentalRatingID: null, releaseYear: '2007', directorName: 'Otto Preminger', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Os Infiltrados', categoryId: '4', parentalRatingID: '2', releaseYear: '2007', directorName: 'Preston Sturges', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Os outros', categoryId: '11', parentalRatingID: null, releaseYear: '2007', directorName: 'Robert Altman', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Os Pilantras', categoryId: null, parentalRatingID: null, releaseYear: '2007', directorName: 'Roman Polanski', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Os sem floresta', categoryId: '14', parentalRatingID: '2', releaseYear: '2007', directorName: 'Sam Peckinpah', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Os Simpsons - 1 Temp - Ep. 1 ao 23', categoryId: '14', parentalRatingID: '2', releaseYear: '2007', directorName: 'Satyajit Ray', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Os Simpsons - 2 Temp - Ep. 1 ao 21', categoryId: '4', parentalRatingID: '5', releaseYear: '2007', directorName: 'Sergei Eisenstein', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Os Simpsons - 3 Temp - Ep. 1 ao 23', categoryId: '7', parentalRatingID: '5', releaseYear: '2007', directorName: 'Sergio Leone', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Os Simpsons - 4 Temp - Ep. 1 ao 22', categoryId: null, parentalRatingID: null, releaseYear: '2007', directorName: 'Sidney Lumet', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Os Simpsons - 5 Temp - Ep. 1 ao 22', categoryId: '4', parentalRatingID: null, releaseYear: '2007', directorName: 'Stanley Kubrick', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Os Simpsons - 6 Temp - Ep. 1 ao 20', categoryId: '2', parentalRatingID: '6', releaseYear: '2007', directorName: 'Steven Spielberg', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Os Simpsons - 7 Temp - Ep. 1 ao 24', categoryId: '12', parentalRatingID: null, releaseYear: '2007', directorName: 'Tim Burton', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Os Simpsons - 8 Temp - Ep. 1 ao 12', categoryId: '7', parentalRatingID: '6', releaseYear: '2007', directorName: 'Vincente Minnelli', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Os Simpson no Brasil', categoryId: '2', parentalRatingID: '6', releaseYear: '2007', directorName: 'Werner Herzog', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Os Simpsons - O Filme', categoryId: '13', parentalRatingID: '2', releaseYear: '2007', directorName: 'William Wyler', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Os Simpsons - O Filme', categoryId: '12', parentalRatingID: '1', releaseYear: '2007', directorName: 'Woody Allen', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Os Supremos', categoryId: '19', parentalRatingID: '5', releaseYear: '2007', directorName: 'Yasujiro Ozu', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Osmose Jones', categoryId: '7', parentalRatingID: null, releaseYear: '2007', directorName: 'Akira Kurosawa', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Paixão de Cristo ', categoryId: '4', parentalRatingID: null, releaseYear: '2007', directorName: 'Alfred Hitchcock', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Pânico 1', categoryId: '7', parentalRatingID: null, releaseYear: '2007', directorName: 'Bernardo Bertolucci', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Pânico 2', categoryId: '23', parentalRatingID: '5', releaseYear: '2007', directorName: 'Billy Wilder', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Panico 3 ', categoryId: '3', parentalRatingID: '6', releaseYear: '2007', directorName: 'Charlie Chaplin', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Pânico na floresta', categoryId: '6', parentalRatingID: '5', releaseYear: '2007', directorName: 'D.W. Griffith', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Pânico na floresta 2', categoryId: '12', parentalRatingID: null, releaseYear: '2007', directorName: 'David Lean', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Pantera Cor de Rosa - Filme', categoryId: '2', parentalRatingID: '5', releaseYear: '2007', directorName: 'Douglas Sirk', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Pantera Cor de Rosa Epis. 1 ao 90', categoryId: null, parentalRatingID: '1', releaseYear: '2007', directorName: 'Ernst Lubitsch', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Pantera Cor de Rosa Epis. 91 ao 130', categoryId: null, parentalRatingID: null, releaseYear: '2007', directorName: 'F.W. Murnau', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Paragráfo 78 A Operação Secreta', categoryId: '12', parentalRatingID: null, releaseYear: '2007', directorName: 'Federico Fellini', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Pateta ', categoryId: '24', parentalRatingID: '2', releaseYear: '2007', directorName: 'Francis Ford Coppola', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Pearl Harbor', categoryId: '21', parentalRatingID: null, releaseYear: '2007', directorName: 'François Truffaut', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Pecado Original', categoryId: '19', parentalRatingID: '5', releaseYear: '2007', directorName: 'Frank Capra', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Perseguição', categoryId: '12', parentalRatingID: '6', releaseYear: '2007', directorName: 'Fritz Lang', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Peter Pan 2003', categoryId: '13', parentalRatingID: '1', releaseYear: '2007', directorName: 'George Cukor', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Pica Pau - 28 episódios', categoryId: '17', parentalRatingID: '5', releaseYear: '2007', directorName: 'Henry King', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Pica Pau - epis. 01 ao 15 + 195 e 196', categoryId: '18', parentalRatingID: '6', releaseYear: '2007', directorName: 'Howard Hawks', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Pink Flamingos', categoryId: '4', parentalRatingID: '5', releaseYear: '2007', directorName: 'Ingmar Bergman', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Piratas do Caribe 2', categoryId: null, parentalRatingID: '1', releaseYear: '2007', directorName: 'Jacques Tati', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Piratas do Caribe 3 - No Fim do Mundo', categoryId: '7', parentalRatingID: null, releaseYear: '2007', directorName: 'Jean Renoir', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Piratas do Vale do Silicio', categoryId: null, parentalRatingID: null, releaseYear: '1999', directorName: 'Jean-Luc Godard', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Planeta dos macacos', categoryId: '4', parentalRatingID: '1', releaseYear: '1999', directorName: 'John Ford', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Planeta dos macacos - A Batalha do Planeta dos M', categoryId: '24', parentalRatingID: '5', releaseYear: '1999', directorName: 'John Huston', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Planeta dos macacos - A fuga do planeta dos M', categoryId: '14', parentalRatingID: '1', releaseYear: '1999', directorName: 'Jonathan Demme', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Planeta dos macacos - De volta ao Planeta dos M', categoryId: '14', parentalRatingID: null, releaseYear: '1999', directorName: 'Josef von Sternberg', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Planeta Vermelho', categoryId: '11', parentalRatingID: null, releaseYear: '1999', directorName: 'Louis Malle', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Platoon', categoryId: null, parentalRatingID: '2', releaseYear: '1999', directorName: 'Luis Buñuel', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Pocahontas 2', categoryId: '1', parentalRatingID: '6', releaseYear: '1999', directorName: 'Martin Scorsese', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Ponte para Terab', categoryId: null, parentalRatingID: null, releaseYear: '1999', directorName: 'Max Ophüls', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Population 436 ', categoryId: null, parentalRatingID: '1', releaseYear: '1999', directorName: 'Michael Powell', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Poseidon ', categoryId: '3', parentalRatingID: '5', releaseYear: '1999', directorName: 'Nicholas Ray', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Premonição', categoryId: null, parentalRatingID: '2', releaseYear: '2007', directorName: 'Orson Welles', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Premonição', categoryId: '18', parentalRatingID: null, releaseYear: '2007', directorName: 'Otto Preminger', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Premonição 2', categoryId: '7', parentalRatingID: null, releaseYear: '2007', directorName: 'Preston Sturges', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Premonição 3', categoryId: '11', parentalRatingID: '2', releaseYear: '2007', directorName: 'Robert Altman', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Principe do Egito', categoryId: '24', parentalRatingID: '2', releaseYear: '2007', directorName: 'Roman Polanski', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Prison Break - 1 temp. Epis. 1 ao 22', categoryId: '16', parentalRatingID: '1', releaseYear: '2007', directorName: 'Sam Peckinpah', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Prison Break - 2 temp. Epis. 1 ao 22', categoryId: '23', parentalRatingID: '6', releaseYear: '2007', directorName: 'Satyajit Ray', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Procurando Nemo', categoryId: '14', parentalRatingID: null, releaseYear: '2007', directorName: 'Sergei Eisenstein', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Procuradas', categoryId: '12', parentalRatingID: '1', releaseYear: '2004', directorName: 'Sergio Leone', dubLeg: 'Dublado'   } )
    movies.push( {name: 'PSILove You', categoryId: '12', parentalRatingID: null, releaseYear: '2004', directorName: 'Sidney Lumet', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Pulp Fiction', categoryId: '9', parentalRatingID: '6', releaseYear: '2004', directorName: 'Stanley Kubrick', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Quarteto Fantastico ', categoryId: '3', parentalRatingID: null, releaseYear: '2004', directorName: 'Steven Spielberg', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Quarteto Fantastico e o Surfista Prateado', categoryId: null, parentalRatingID: null, releaseYear: '2004', directorName: 'Tim Burton', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Quebrando Regras - Never Back Down', categoryId: '4', parentalRatingID: null, releaseYear: '2008', directorName: 'Vincente Minnelli', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Quem somos nós', categoryId: '1', parentalRatingID: '2', releaseYear: '2008', directorName: 'Werner Herzog', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Rachas e Baladas (Dolphins)', categoryId: '23', parentalRatingID: '5', releaseYear: '2007', directorName: 'William Wyler', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Rambo IV', categoryId: '7', parentalRatingID: '1', releaseYear: '2008', directorName: 'Woody Allen', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Rainha dos Condenados - Queen of the Damned', categoryId: null, parentalRatingID: '1', releaseYear: '2008', directorName: 'Yasujiro Ozu', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Ratatouille', categoryId: null, parentalRatingID: null, releaseYear: '2008', directorName: 'Akira Kurosawa', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Reeker', categoryId: null, parentalRatingID: '5', releaseYear: '2008', directorName: 'Alfred Hitchcock', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Reine sobre mim.', categoryId: null, parentalRatingID: null, releaseYear: '2008', directorName: 'Bernardo Bertolucci', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Regras de Guerra', categoryId: '13', parentalRatingID: '6', releaseYear: '2008', directorName: 'Billy Wilder', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Rei Leão 2', categoryId: '19', parentalRatingID: null, releaseYear: '2008', directorName: 'Charlie Chaplin', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Reino de Fogo', categoryId: '3', parentalRatingID: '2', releaseYear: '2008', directorName: 'D.W. Griffith', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Replicante', categoryId: '12', parentalRatingID: '5', releaseYear: '2008', directorName: 'David Lean', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Resident Evil ', categoryId: null, parentalRatingID: '1', releaseYear: '2008', directorName: 'Douglas Sirk', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Resident Evil - Apocalypse', categoryId: '24', parentalRatingID: '6', releaseYear: '2008', directorName: 'Ernst Lubitsch', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Resident Evil 2', categoryId: null, parentalRatingID: '2', releaseYear: '2008', directorName: 'F.W. Murnau', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Resident Evil 3', categoryId: '19', parentalRatingID: '1', releaseYear: '2008', directorName: 'Federico Fellini', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Revelação de um crime', categoryId: '21', parentalRatingID: null, releaseYear: '2008', directorName: 'Francis Ford Coppola', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Rios Vermelhos', categoryId: '19', parentalRatingID: null, releaseYear: '2008', directorName: 'François Truffaut', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Risco Duplo', categoryId: '18', parentalRatingID: null, releaseYear: '2008', directorName: 'Frank Capra', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Rôbos ', categoryId: '13', parentalRatingID: '5', releaseYear: '2008', directorName: 'Fritz Lang', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Sahara ', categoryId: '22', parentalRatingID: null, releaseYear: '2005', directorName: 'George Cukor', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Sangue Negro - There will be blood', categoryId: '3', parentalRatingID: '6', releaseYear: '2007', directorName: 'Henry King', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Scooby Doo', categoryId: '8', parentalRatingID: null, releaseYear: '2007', directorName: 'Howard Hawks', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Scooby Doo', categoryId: '17', parentalRatingID: null, releaseYear: '2007', directorName: 'Ingmar Bergman', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Secretária (Secretary) -', categoryId: '2', parentalRatingID: '5', releaseYear: '2002', directorName: 'Jacques Tati', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Se eu fosse você', categoryId: '6', parentalRatingID: null, releaseYear: '2002', directorName: 'Jean Renoir', dubLeg: 'Legendado'   } )
    movies.push( {name: 'See no evil ', categoryId: '2', parentalRatingID: '6', releaseYear: '2002', directorName: 'Jean-Luc Godard', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Selvagem ', categoryId: '17', parentalRatingID: null, releaseYear: '2002', directorName: 'John Ford', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Senhor dos Anéis', categoryId: '13', parentalRatingID: '2', releaseYear: '2002', directorName: 'John Huston', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Senhor dos Anéis - As dua Torres', categoryId: null, parentalRatingID: '6', releaseYear: '2002', directorName: 'Jonathan Demme', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Senhor e Senhora Smith', categoryId: '2', parentalRatingID: null, releaseYear: '2002', directorName: 'Josef von Sternberg', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Senhores do Crime ', categoryId: '12', parentalRatingID: '5', releaseYear: '2007', directorName: 'Louis Malle', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Sete homens e um destino', categoryId: '12', parentalRatingID: '1', releaseYear: '2007', directorName: 'Luis Buñuel', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Seu amor, meu destino', categoryId: '8', parentalRatingID: '1', releaseYear: '2000', directorName: 'Martin Scorsese', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Sex and the City', categoryId: '11', parentalRatingID: '6', releaseYear: '2008', directorName: 'Max Ophüls', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Sexo, Amor e Traição', categoryId: '24', parentalRatingID: null, releaseYear: '2008', directorName: 'Michael Powell', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Shaft', categoryId: '19', parentalRatingID: '5', releaseYear: '2008', directorName: 'Nicholas Ray', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Shaolin Soccer ', categoryId: '18', parentalRatingID: '5', releaseYear: '2008', directorName: 'Orson Welles', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Shrek', categoryId: null, parentalRatingID: '5', releaseYear: '2008', directorName: 'Otto Preminger', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Shrek 2', categoryId: '9', parentalRatingID: null, releaseYear: '2008', directorName: 'Preston Sturges', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Shrek 3', categoryId: '11', parentalRatingID: null, releaseYear: '2008', directorName: 'Robert Altman', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Shrek 3', categoryId: '24', parentalRatingID: '2', releaseYear: '2008', directorName: 'Roman Polanski', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Shutter', categoryId: '18', parentalRatingID: '6', releaseYear: '2008', directorName: 'Sam Peckinpah', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Side Fx', categoryId: null, parentalRatingID: null, releaseYear: '2008', directorName: 'Satyajit Ray', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Silêncio dos Inocentes', categoryId: '21', parentalRatingID: null, releaseYear: '2008', directorName: 'Sergei Eisenstein', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Silent Hill ', categoryId: '13', parentalRatingID: '6', releaseYear: '2008', directorName: 'Sergio Leone', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Sinais', categoryId: '21', parentalRatingID: null, releaseYear: '2008', directorName: 'Sidney Lumet', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Sinbad', categoryId: '13', parentalRatingID: '6', releaseYear: '2008', directorName: 'Stanley Kubrick', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Snake King', categoryId: '18', parentalRatingID: '5', releaseYear: '2008', directorName: 'Steven Spielberg', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Sombras do Passado', categoryId: '11', parentalRatingID: null, releaseYear: '2008', directorName: 'Tim Burton', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Sorte no Amor', categoryId: '13', parentalRatingID: '6', releaseYear: '2008', directorName: 'Vincente Minnelli', dubLeg: 'Dublado'   } )
    movies.push( {name: 'South Park', categoryId: '14', parentalRatingID: '1', releaseYear: '2008', directorName: 'Werner Herzog', dubLeg: 'Legendado'   } )
    movies.push( {name: 'SpiderMan', categoryId: '12', parentalRatingID: null, releaseYear: '2008', directorName: 'William Wyler', dubLeg: 'Legendado'   } )
    movies.push( {name: 'SpiderMan 2', categoryId: '16', parentalRatingID: null, releaseYear: '2008', directorName: 'Woody Allen', dubLeg: 'Legendado'   } )
    movies.push( {name: 'SpiderMan 3', categoryId: '6', parentalRatingID: null, releaseYear: '2008', directorName: 'Yasujiro Ozu', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Spirit - O Corcel Indomavel', categoryId: '8', parentalRatingID: '5', releaseYear: '2008', directorName: 'Akira Kurosawa', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Stargate - A Arca da Verdade - Stargate The Ark of Truth', categoryId: '11', parentalRatingID: null, releaseYear: '2008', directorName: 'Alfred Hitchcock', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Star Wars - Episodio II - Ataque dos Clones', categoryId: '1', parentalRatingID: '5', releaseYear: '2008', directorName: 'Bernardo Bertolucci', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Star Wars 3 - A vingança dos Siths', categoryId: '9', parentalRatingID: '2', releaseYear: '2008', directorName: 'Billy Wilder', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Stargate ', categoryId: '24', parentalRatingID: null, releaseYear: '2008', directorName: 'Charlie Chaplin', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Stigmata', categoryId: '8', parentalRatingID: '6', releaseYear: '2008', directorName: 'D.W. Griffith', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Street Fighter - Desenho', categoryId: '3', parentalRatingID: '2', releaseYear: '2008', directorName: 'David Lean', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Street Fighter II - The Animated Movie', categoryId: '2', parentalRatingID: '6', releaseYear: '2008', directorName: 'Douglas Sirk', dubLeg: 'Legendado'   } )
    movies.push( {name: 'SunShine - Alerta Solar', categoryId: null, parentalRatingID: null, releaseYear: '2008', directorName: 'Ernst Lubitsch', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Super-Herói - O Filme', categoryId: '19', parentalRatingID: '2', releaseYear: '2008', directorName: 'F.W. Murnau', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Super Maquina 2008', categoryId: '16', parentalRatingID: null, releaseYear: '2008', directorName: 'Federico Fellini', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Super Nova', categoryId: '18', parentalRatingID: '6', releaseYear: '2008', directorName: 'Francis Ford Coppola', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Superman o retorno', categoryId: null, parentalRatingID: '1', releaseYear: '2008', directorName: 'François Truffaut', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Swat', categoryId: '8', parentalRatingID: '1', releaseYear: '2008', directorName: 'Frank Capra', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Swat - Comando Especial ', categoryId: null, parentalRatingID: '2', releaseYear: '2008', directorName: 'Fritz Lang', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Swordfish : A Senha', categoryId: '3', parentalRatingID: '5', releaseYear: '2008', directorName: 'George Cukor', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Ta todo mundo louco ', categoryId: '13', parentalRatingID: '1', releaseYear: '2008', directorName: 'Henry King', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Takedown', categoryId: '11', parentalRatingID: null, releaseYear: '2008', directorName: 'Howard Hawks', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Tarzan', categoryId: '4', parentalRatingID: null, releaseYear: '2008', directorName: 'Ingmar Bergman', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Te pego la fora', categoryId: '12', parentalRatingID: '2', releaseYear: '2008', directorName: 'Jacques Tati', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Terapia do Amor ', categoryId: null, parentalRatingID: '1', releaseYear: '2005', directorName: 'Jean Renoir', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Teenagers as Apimentadas', categoryId: '2', parentalRatingID: null, releaseYear: '2005', directorName: 'Jean-Luc Godard', dubLeg: 'Legendado'   } )
    movies.push( {name: 'The Hills Have Eyes', categoryId: '7', parentalRatingID: null, releaseYear: '2005', directorName: 'John Ford', dubLeg: 'Legendado'   } )
    movies.push( {name: 'The Hulk', categoryId: '13', parentalRatingID: '2', releaseYear: '2005', directorName: 'John Huston', dubLeg: 'Legendado'   } )
    movies.push( {name: 'The Jacket', categoryId: null, parentalRatingID: null, releaseYear: '2005', directorName: 'Jonathan Demme', dubLeg: 'Legendado'   } )
    movies.push( {name: 'The Last Hangman', categoryId: '19', parentalRatingID: '6', releaseYear: '2005', directorName: 'Josef von Sternberg', dubLeg: 'Legendado'   } )
    movies.push( {name: 'The Unknown', categoryId: '12', parentalRatingID: '6', releaseYear: '2005', directorName: 'Louis Malle', dubLeg: 'Legendado'   } )
    movies.push( {name: 'The Zodiac', categoryId: null, parentalRatingID: '5', releaseYear: '2005', directorName: 'Luis Buñuel', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Tinha de ser você', categoryId: null, parentalRatingID: '6', releaseYear: '2005', directorName: 'Martin Scorsese', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Todo Mundo em Panico', categoryId: '18', parentalRatingID: '6', releaseYear: '2005', directorName: 'Max Ophüls', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Todo mundo em pânico 3', categoryId: '17', parentalRatingID: '6', releaseYear: '2005', directorName: 'Michael Powell', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Todo mundo em pânico 4', categoryId: '7', parentalRatingID: '6', releaseYear: '2005', directorName: 'Nicholas Ray', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Tomb Raider', categoryId: null, parentalRatingID: '2', releaseYear: '2005', directorName: 'Orson Welles', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Tomb Raider - A Origem da vida', categoryId: '6', parentalRatingID: '2', releaseYear: '2005', directorName: 'Otto Preminger', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Toy Story 2', categoryId: '23', parentalRatingID: null, releaseYear: '2005', directorName: 'Preston Sturges', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Toy Story 2', categoryId: '21', parentalRatingID: '1', releaseYear: '2005', directorName: 'Robert Altman', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Transformers - O Filme', categoryId: '19', parentalRatingID: null, releaseYear: '2007', directorName: 'Roman Polanski', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Transformes desenho', categoryId: '19', parentalRatingID: '6', releaseYear: '2007', directorName: 'Sam Peckinpah', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Tratamento de choque', categoryId: '8', parentalRatingID: '2', releaseYear: '2007', directorName: 'Satyajit Ray', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Triplo X', categoryId: '8', parentalRatingID: null, releaseYear: '2007', directorName: 'Sergei Eisenstein', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Triplo XXX 2 - Estado de emergência', categoryId: '21', parentalRatingID: null, releaseYear: '2007', directorName: 'Sergio Leone', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Tróia', categoryId: '21', parentalRatingID: '1', releaseYear: '2007', directorName: 'Sidney Lumet', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Tropas Estelares 2', categoryId: '24', parentalRatingID: '5', releaseYear: '2007', directorName: 'Stanley Kubrick', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Turbinados - Street Racer', categoryId: '19', parentalRatingID: null, releaseYear: '2008', directorName: 'Steven Spielberg', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Turistas', categoryId: '22', parentalRatingID: '5', releaseYear: '2008', directorName: 'Tim Burton', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Ultraviolet', categoryId: '24', parentalRatingID: null, releaseYear: '2008', directorName: 'Vincente Minnelli', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Um Principe em minha vida', categoryId: '2', parentalRatingID: null, releaseYear: '2008', directorName: 'Werner Herzog', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Um tira muito suspeito', categoryId: null, parentalRatingID: null, releaseYear: '2008', directorName: 'William Wyler', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Um Verão Para Toda Vida', categoryId: '3', parentalRatingID: '6', releaseYear: '2008', directorName: 'Woody Allen', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Uma cada de pernas pro ar', categoryId: '16', parentalRatingID: null, releaseYear: '2008', directorName: 'Yasujiro Ozu', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Uma Noite no Museu', categoryId: '17', parentalRatingID: '2', releaseYear: '2008', directorName: 'Akira Kurosawa', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Uma Nova Cinderela', categoryId: '9', parentalRatingID: null, releaseYear: '2008', directorName: 'Alfred Hitchcock', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Underworld', categoryId: '24', parentalRatingID: '6', releaseYear: '2008', directorName: 'Bernardo Bertolucci', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Underworld Evolution', categoryId: '6', parentalRatingID: '2', releaseYear: '2008', directorName: 'Billy Wilder', dubLeg: 'Legendado'   } )
    movies.push( {name: 'V de Vingança', categoryId: '4', parentalRatingID: null, releaseYear: '2008', directorName: 'Charlie Chaplin', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Valiant', categoryId: '18', parentalRatingID: null, releaseYear: '2008', directorName: 'D.W. Griffith', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Vampiros do deserto', categoryId: '1', parentalRatingID: '5', releaseYear: '2008', directorName: 'David Lean', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Vanilla Sky ', categoryId: '23', parentalRatingID: '1', releaseYear: '2008', directorName: 'Douglas Sirk', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Velozes e Furiosos', categoryId: '1', parentalRatingID: null, releaseYear: '2008', directorName: 'Ernst Lubitsch', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Velozes e Furiosos - Desafio em Tokyo', categoryId: '14', parentalRatingID: '5', releaseYear: '2008', directorName: 'F.W. Murnau', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Viagem ao Centro da Terra - Journey to the Center of the World', categoryId: null, parentalRatingID: '1', releaseYear: '2008', directorName: 'Federico Fellini', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Vida Bandida', categoryId: null, parentalRatingID: null, releaseYear: '2008', directorName: 'Francis Ford Coppola', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Vidas Secas', categoryId: '12', parentalRatingID: '5', releaseYear: '1963', directorName: 'François Truffaut', dubLeg: 'Legendado'   } )
    movies.push( {name: 'vida no ventre', categoryId: '4', parentalRatingID: '1', releaseYear: '1963', directorName: 'Frank Capra', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Vizinhança do barulho', categoryId: '12', parentalRatingID: '5', releaseYear: '1963', directorName: 'Fritz Lang', dubLeg: 'Legendado'   } )
    movies.push( {name: 'War Rogue - O Assassino', categoryId: null, parentalRatingID: '5', releaseYear: '1963', directorName: 'George Cukor', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Wimbledon O Jogo Do Amor', categoryId: '11', parentalRatingID: '5', releaseYear: '1963', directorName: 'Henry King', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Wolf Creek', categoryId: '17', parentalRatingID: '1', releaseYear: '1963', directorName: 'Howard Hawks', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Xeque-Mate (Lucky Number Slevin) ', categoryId: '17', parentalRatingID: null, releaseYear: '2006', directorName: 'Ingmar Bergman', dubLeg: 'Dublado'   } )
    movies.push( {name: 'X-Men', categoryId: null, parentalRatingID: '2', releaseYear: '2006', directorName: 'Jacques Tati', dubLeg: 'Legendado'   } )
    movies.push( {name: 'X-Men', categoryId: '11', parentalRatingID: '1', releaseYear: '2006', directorName: 'Jean Renoir', dubLeg: 'Dublado'   } )
    movies.push( {name: 'X-Men 3', categoryId: null, parentalRatingID: null, releaseYear: '2006', directorName: 'Jean-Luc Godard', dubLeg: 'Legendado'   } )
    movies.push( {name: 'X-Men - 1 Temp - Ep. 1 ao 13', categoryId: '4', parentalRatingID: null, releaseYear: '2006', directorName: 'John Ford', dubLeg: 'Dublado'   } )
    movies.push( {name: 'X-Men - 2 Temp - Ep. 1 ao 13', categoryId: '16', parentalRatingID: null, releaseYear: '2006', directorName: 'John Huston', dubLeg: 'Dublado'   } )
    movies.push( {name: 'X-Men - 3 Temp - Ep. 1 ao 19', categoryId: '22', parentalRatingID: null, releaseYear: '2006', directorName: 'Jonathan Demme', dubLeg: 'Dublado'   } )
    movies.push( {name: 'X-Men - 4 Temp - Ep. 1 ao 17', categoryId: '6', parentalRatingID: '2', releaseYear: '2006', directorName: 'Josef von Sternberg', dubLeg: 'Dublado'   } )
    movies.push( {name: 'X-Men - 5 Temp - Ep. 1 ao 14', categoryId: '1', parentalRatingID: null, releaseYear: '2006', directorName: 'Louis Malle', dubLeg: 'Dublado'   } )
    movies.push( {name: 'X-Men Evolution - Ep. 1 ao 42', categoryId: '11', parentalRatingID: null, releaseYear: '2006', directorName: 'Luis Buñuel', dubLeg: 'Dublado'   } )
    movies.push( {name: 'Xeque-Mate', categoryId: '7', parentalRatingID: '5', releaseYear: '2006', directorName: 'Martin Scorsese', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Xuxa Abracadabra', categoryId: '1', parentalRatingID: '2', releaseYear: '2006', directorName: 'Max Ophüls', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Xuxa circo 5 SPB', categoryId: '22', parentalRatingID: null, releaseYear: '2006', directorName: 'Michael Powell', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Xuxa só para baixinhos 3', categoryId: '7', parentalRatingID: '2', releaseYear: '2006', directorName: 'Nicholas Ray', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Zathura', categoryId: '2', parentalRatingID: '2', releaseYear: '2006', directorName: 'Orson Welles', dubLeg: 'Legendado'   } )
    movies.push( {name: 'Zoolander', categoryId: '16', parentalRatingID: null, releaseYear: '2006', directorName: 'Otto Preminger', dubLeg: 'Legendado'   } )
               
    db.movies.bulkCreate(movies)
        .then((resp)=>{ console.log("Criando classificação movies") })
        // .catch(err=>  { console.log(err) })
        .catch(err=>  { console.log(err.code, err.message) })
    





    